### PR TITLE
Fix IE, userfriendly, autosolve, directional lines

### PR DESCRIPTION
**Pull request by Nickardson**
I made most of these changes for my own purposes, you are welcome to them if it fits your vision.

Fixed IE compatibility by removing 'for of' loop and 'output' tag.

When the reveal bar is at the maximum, it will stay at the maximum until
changed by the user.

Added two optional features:
- Autosolve - Any changes to the board will attempt to be solved.
- Directional lines - When turned on, lines are thicker in one direction,
  to give a sense of which direction to go.

lines

### CODE REVIEW

**Comment by denilsonsa** [comment]
Thanks for the pull request!

I didn't care about IE (which is always lagging behind other browsers), but I'll probably accept those changes.

I like the idea of directional lines, but I'll probably implement it using [SVG markers](http://www.w3.org/TR/SVG/painting.html#MarkerMidProperty) instead ([like this](http://tutorials.jenkov.com/svg/marker-element.html#referencing-markers-from-a-path)).

Autosolve is a nice feature, but can introduce a lot of slowdown (see issue #1). I should probably learn [HTML5 Web Workers](http://www.w3.org/TR/workers/) and put the solving algorithm in a background thread before adding the autosolve.

That "keep the slider at maximum" feature is something I wanted from the beginning, but then forgot! Thanks!

I'll dive into the code later.

**Comment by denilsonsa** [comment]
Keeping track of which features I'm merging into the project.
- [x] `<output>` → `<div>`
- [x] Removing `for of`
- [x] Keep slider at maximum
- [x] Directional arrows
- [x] Web Workers
- [x] Auto-solve

I hope you like the way I've implemented the directional arrows. :) And I haven't tested it on IE.

**Comment by Nickardson** [comment]
Those arrows are much cooler!
It unfortunately didn't seem to work in IE, I'll try look into what's causing the blank canvas.

**Comment by denilsonsa** [comment]
@Nickardson, try again. I've fixed the arrow rendering in Firefox, it may have fixed in IE too. (unless the IE issue is much larger than what I thought…)

**Comment by Nickardson** [comment]
Rendering is fixed. Not sure if it's just a weird IE bug on my side, the reveal range 'input' listener isn't called. I got it to work by adding

``` javascript
revealrange.addEventListener('change', revealrange_input_handler);
```

at https://github.com/denilsonsa/lyne-solver/blob/master/ui.js#L321

**Comment by denilsonsa** [comment]
Thanks for your pull request! I believe all features from it have already been merged into the main code, so I'm closing this. Feel free to open more issues or pull requests if you have something else.

**Pull request closed without merging**
